Repository cinder/Cinder, pull requests merged in 2018-11, with the labels that each got.

#2042 Add OSC Message support to access the sender's port
  blocks/OSC/src/cinder/osc/Osc.cpp
  blocks/OSC/src/cinder/osc/Osc.h
  blocks/OSC/test/Test/src/TestApp.cpp
Labels: networking

#2050 Fix RPi build process.
  proj/cmake/libcinder_configure.cmake
  src/cinder/app/Window.cpp
Labels: raspberry pi

#2053 CMake samples fixes.
  samples/CameraPersp/proj/cmake/CMakeLists.txt
  samples/FrustumCulling/proj/cmake/CMakeLists.txt
  samples/Kaleidoscope/proj/cmake/CMakeLists.txt
  samples/MandelbrotGLSL/proj/cmake/CMakeLists.txt
  samples/QuaternionAccum/proj/cmake/CMakeLists.txt
  samples/RDiffusion/proj/cmake/CMakeLists.txt
  samples/StereoscopicRendering/proj/cmake/CMakeLists.txt
  samples/SurfaceBasic/proj/cmake/CMakeLists.txt
  samples/TextTest/proj/cmake/CMakeLists.txt
  samples/VoronoiGpu/proj/cmake/CMakeLists.txt
Labels: build system

#2054 Enable ci::Serial on Linux.
  proj/cmake/libcinder_source_files.cmake
  src/cinder/Serial.cpp
Labels: linux

#2059 Fix xcode build path in OSX instructions
  docs/htmlsrc/guides/git/index.html
Labels: docs

#2058 fix for character animOut
  samples/_timeline/TextInputTween/src/TextInputTweenApp.cpp
Labels: sample
